// pages/visualization/distributedMaps.vue
<template>
  <div class="relative w-full h-screen overflow-hidden bg-black">
    <RankingList :data="rankList" />
    <div ref="container" class="w-full h-full"></div>
    
    <!-- Loading overlay -->
    <div v-if="loading" class="absolute inset-0 flex items-center justify-center bg-black/50 z-50">
      <div class="text-white text-xl">Loading...</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import * as THREE from 'three'
import { onMounted, onUnmounted, ref, shallowRef } from 'vue'
import ThreeCore from '@/utils/threeCore'
import { BASE_IMG } from '@/utils/ipConfig'
import { getDistributedMaps } from '@/api/statistics'
import RankingList from '@/components/visualization/RankingList.vue'

// SEO
useHead({
  title: 'Lo娘分布地图 - Lo研社',
})

const container = ref<HTMLElement | null>(null)
const loading = ref(true)
const rankList = ref<any[]>([])
const threeCore = shallowRef<ThreeCore | null>(null)

// Map state
const latRange = ref({ min: Infinity, max: -Infinity })
const lonRange = ref({ min: Infinity, max: -Infinity })

// Helper to convert lat/lon to 3D coordinates (using simple linear projection as requested)
const latLonToXYZ = (lat: number, lon: number) => {
  const lRange = latRange.value
  const lnRange = lonRange.value
  
  if (lRange.min === Infinity || lnRange.min === Infinity) return new THREE.Vector3(0, 0, 0)
  
  // Center the map at (0,0,0) by subtracting 0.5 and then scaling
  // The original code mapped to 0..1000. Let's map to -500..500 for better centering
  const x = ((lon - lnRange.min) / (lnRange.max - lnRange.min) - 0.5) * 1000
  const y = ((lat - lRange.min) / (lRange.max - lRange.min) - 0.5) * 1000
  const z = 0
  
  return new THREE.Vector3(x, y, z)
}

// Calculate ranges from GeoJSON
const calculateLatLonRange = (geojson: any) => {
  let lRange = { min: Infinity, max: -Infinity }
  let lnRange = { min: Infinity, max: -Infinity }

  geojson.features.forEach((feature: any) => {
    const processRing = (ring: number[][]) => {
      ring.forEach(([lon, lat]) => {
        lRange.min = Math.min(lRange.min, lat)
        lRange.max = Math.max(lRange.max, lat)
        lnRange.min = Math.min(lnRange.min, lon)
        lnRange.max = Math.max(lnRange.max, lon)
      })
    }

    if (feature.geometry.type === 'Polygon') {
      feature.geometry.coordinates.forEach(processRing)
    } else if (feature.geometry.type === 'MultiPolygon') {
      feature.geometry.coordinates.forEach((polygon: any) => {
        polygon.forEach(processRing)
      })
    }
  })

  return { latRange: lRange, lonRange: lnRange }
}

// Create Map Mesh from GeoJSON
const createGeoJsonMap = (geojson: any, options: { totalCount: number }) => {
  const group = new THREE.Group()
  const material = new THREE.MeshPhongMaterial({ 
    color: 0x333333, 
    transparent: true, 
    opacity: 0.9,
    side: THREE.DoubleSide
  })
  const lineMaterial = new THREE.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.3 })

  geojson.features.forEach((feature: any) => {
    const drawPolygon = (coordinates: number[][]) => {
      const shape = new THREE.Shape()
      
      coordinates.forEach((point, i) => {
        const [lon, lat] = point
        const pos = latLonToXYZ(lat, lon)
        if (i === 0) {
          shape.moveTo(pos.x, pos.y)
        } else {
          shape.lineTo(pos.x, pos.y)
        }
      })

      const geometry = new THREE.ExtrudeGeometry(shape, {
        depth: 2,
        bevelEnabled: false
      })

      // Determine color based on rank if available
      let color = new THREE.Color(0x333333)
      if (feature.rank) {
        // Top ranks get brighter colors
        if (feature.rank <= 3) {
           color = new THREE.Color().setHSL(0.1, 0.8, 0.6) // Gold-ish
        } else if (feature.rank <= 10) {
           color = new THREE.Color().setHSL(0.6, 0.5, 0.5) // Blue-ish
        } else {
           // Gradient based on rank
           color = new THREE.Color().setHSL(0.6, 0.3, 0.3 + (1/feature.rank)*0.5)
        }
      } else if (feature.count > 0) {
          color = new THREE.Color().setHSL(0.6, 0.5, 0.4)
      }

      const mat = new THREE.MeshPhongMaterial({
        color: color,
        transparent: true,
        opacity: 0.9,
        side: THREE.DoubleSide
      })

      const mesh = new THREE.Mesh(geometry, mat)
      mesh.userData = feature.properties
      mesh.receiveShadow = true
      mesh.castShadow = true
      group.add(mesh)

      // Add border line
      const points = coordinates.map(([lon, lat]) => latLonToXYZ(lat, lon))
      const lineGeometry = new THREE.BufferGeometry().setFromPoints(points)
      const line = new THREE.Line(lineGeometry, lineMaterial)
      // Lift line slightly to avoid z-fighting
      line.position.z = 2.1
      group.add(line)
    }

    if (feature.geometry.type === 'Polygon') {
      feature.geometry.coordinates.forEach(drawPolygon)
    } else if (feature.geometry.type === 'MultiPolygon') {
      feature.geometry.coordinates.forEach((polygon: any) => {
        polygon.forEach(drawPolygon)
      })
    }
  })

  return group
}

// Create Cylinder at Lat/Lng
const createCylinderAtLatLng = (lat: number, lon: number, height: number, name: string) => {
  const pos = latLonToXYZ(lat, lon)
  
  // Ensure minimum height for visibility
  const h = Math.max(height, 2)
  
  const geometry = new THREE.CylinderGeometry(0.5, 0.5, h, 8)
  // Shift center so cylinder grows upwards
  geometry.translate(0, h / 2, 0)
  // Rotate to align with Z axis (since map is on XY plane in the projection logic)
  geometry.rotateX(Math.PI / 2)
  
  const material = new THREE.MeshPhongMaterial({ color: 0x00ff00 }) // Green bars
  const mesh = new THREE.Mesh(geometry, material)
  
  mesh.position.set(pos.x, pos.y, 2) // On top of map
  mesh.userData = { name, height }
  mesh.castShadow = true
  mesh.receiveShadow = true
  
  return mesh
}

// Rank distribution helper
const rankDistribution = (features: any[], topN: number | null = null) => {
  const total = features.reduce((sum, f) => sum + (f.count || 0), 0)
  const sorted = [...features]
    .filter(f => f.count > 0)
    .sort((a, b) => b.count - a.count)
    .map((f, index) => ({
      rank: index + 1,
      name: f.name,
      count: f.count,
      percent: total > 0 ? ((f.count / total) * 100).toFixed(2) + '%' : '0%'
    }))
  return topN ? sorted.slice(0, topN) : sorted
}

onMounted(async () => {
  if (!container.value) return

  // Initialize ThreeCore with high performance settings
  const app = new ThreeCore({
    antialias: true,
    alpha: true,
    cameraPosition: { x: 0, y: 0, z: 600 },
    enableOrbitControls: true,
    pixelRatio: window.devicePixelRatio,
    // clearColor: 0x000000 
  })
  
  app.mount(container.value)
  app.startAnimationLoop()
  threeCore.value = app
  
  // Use Bloom
  app.toggleBloom(true)
  if (app.bloomPass) {
      app.bloomPass.strength = 0.5
      app.bloomPass.radius = 0.5
      app.bloomPass.threshold = 0
  }

  // Clear existing lights and setup scene specific lights
  // app.scene.remove(...app.scene.children.filter(o => o instanceof THREE.Light)) // Rough cleanup if needed
  
  // Setup lights based on the requested "old code" style
  // Ambient Light
  if (app.lights?.ambient) app.lights.ambient.intensity = 2
  
  // Directional Light with Shadows
  if (app.lights?.directional) {
      const dirLight = app.lights.directional
      dirLight.intensity = 6
      dirLight.position.set(50, 100, 50)
      dirLight.castShadow = true
      dirLight.shadow.mapSize.width = 4096
      dirLight.shadow.mapSize.height = 4096
      dirLight.shadow.bias = -0.0001
      dirLight.shadow.camera.near = 0.5
      dirLight.shadow.camera.far = 500
      dirLight.shadow.camera.left = -300
      dirLight.shadow.camera.right = 300
      dirLight.shadow.camera.top = 300
      dirLight.shadow.camera.bottom = -300
      
      // Add helper for debugging if needed
      // const helper = new THREE.DirectionalLightHelper(dirLight)
      // app.scene.add(helper)
  }

  try {
    // 1. Fetch World JSON (changed from geoJson.json)
    const geoJsonRes = await fetch(BASE_IMG + 'ssr/world.json')
    if (!geoJsonRes.ok) throw new Error('Failed to load world.json')
    const geojson = await geoJsonRes.json()

    // 2. Calculate Ranges
    const ranges = calculateLatLonRange(geojson)
    latRange.value = ranges.latRange
    lonRange.value = ranges.lonRange

    // 3. Fetch Statistics Data
    const statsRes = await getDistributedMaps()
    const statsData = statsRes.data

    // 4. Merge Data
    let totalCount = 0
    const features = geojson.features.map((item: any) => {
        return {
            name: item.properties.name,
            center: item.properties.center, 
            count: 0
        }
    })

    statsData.forEach((child) => {
        const index = features.findIndex((item: any) => item.name && item.name.includes(child.ip_location))
        if (index !== -1) {
            features[index].count = child.COUNT
            totalCount += child.COUNT
            geojson.features[index].count = child.COUNT
        }
    })

    // 5. Rank Logic (from old React code)
    const provinceName = [
        '北京市', '天津市', '河北省', '山西省', '内蒙古自治区', '辽宁省', '吉林省', '黑龙江省',
        '上海市', '江苏省', '浙江省', '安徽省', '福建省', '江西省', '山东省', '河南省',
        '湖北省', '湖南省', '广东省', '广西壮族自治区', '海南省', '重庆市', '四川省', '贵州省',
        '云南省', '西藏自治区', '陕西省', '甘肃省', '青海省', '宁夏回族自治区', '新疆维吾尔自治区',
        '台湾省', '香港特别行政区', '澳门特别行政区'
    ];
    
    // Rank features for coloring logic
    const chinaFeaturesWithIndex = geojson.features
        .map((f: any, i: number) => ({ feature: f, index: i }))
        .filter((item: any) => provinceName.includes(item.feature.properties.name));
        
    chinaFeaturesWithIndex
        .sort((a: any, b: any) => (b.feature.count || 0) - (a.feature.count || 0))
        .forEach((item: any, i: number) => {
          geojson.features[item.index].rank = i + 1;
        });

    rankList.value = rankDistribution(features)

    // 6. Create Map
    const mapGroup = createGeoJsonMap(geojson, { totalCount })
    app.scene.add(mapGroup)

    // 7. Create Cylinders (Data Bars)
    const barsGroup = new THREE.Group()
    features.forEach((child: any) => {
        if (child.count > 0 && child.center) {
            const height = (child.count / totalCount) * 500 // Scale factor
            const cylinder = createCylinderAtLatLng(child.center[1], child.center[0], height, `${child.name} ${child.count}`)
            
            // Color coding based on count intensity
            const intensity = Math.min(child.count / (totalCount * 0.1), 1)
            const color = new THREE.Color().setHSL(0.3 - intensity * 0.3, 1.0, 0.5) // Green to Red
            if (cylinder.material instanceof THREE.MeshPhongMaterial) {
               cylinder.material.color = color
               // Add emissive for bloom
               cylinder.material.emissive = color
               cylinder.material.emissiveIntensity = 0.5
            }
            
            // Enable bloom layer for this object
            app.addBloomObject(cylinder)
            
            barsGroup.add(cylinder)
        }
    })
    app.scene.add(barsGroup)

    // Breathing Animation
    const animateBreathing = () => {
        const time = Date.now() * 0.002;
        barsGroup.children.forEach((child) => {
            if (child instanceof THREE.Mesh && child.material instanceof THREE.MeshPhongMaterial) {
                // Pulse emissive intensity
                const pulse = (Math.sin(time) + 1) * 0.5 * 0.5 + 0.2; // 0.2 to 0.7
                child.material.emissiveIntensity = pulse;
            }
        });
    }
    app.addAnimationCallback(animateBreathing);

    // Adjust Camera Focus
    const centerPos = latLonToXYZ(35, 105) // China center roughly
    app.controls.target.set(centerPos.x, centerPos.y, 0)
    app.camera.position.set(centerPos.x, centerPos.y - 300, 300)
    app.camera.lookAt(centerPos.x, centerPos.y, 0)
    app.controls.update()

  } catch (e) {
    console.error('Failed to load map data', e)
  } finally {
    loading.value = false
  }
})

onUnmounted(() => {
  if (threeCore.value) {
    threeCore.value.dispose()
  }
})
</script>

<style scoped>
/* Add any custom styles here */
</style>

// pages/visualization/distributedMaps/distributedMaps.jsx
import React from "react";
import * as THREE from 'three'

import "./index.less";
import app from './app.js'
import './load.js'
import {
  DownOutlined, UpOutlined
} from '@ant-design/icons';
import { Button, Drawer, Collapse, message, Input, Tag, Tabs } from 'antd';
import RankingList from './rankList.jsx'
import { getDistributedMaps } from '../../api/statistics.js'
// const geojson = require('./geoJson.json')
const geojson = require('./world.json')

class Index extends React.Component {  
    state = {
      id: null,
      latRange: null,
      lonRange: null,
      features: [], // 省
      rank_list: []
    }
    constructor(props) {
      super(props);
      this.canvasRef = React.createRef();
    }
    latLonToXYZ(lat, lon) {
      const { lonRange, latRange } = this.state
      const x = (lon - lonRange.min) / (lonRange.max - lonRange.min) * 1000;  // 经度映射到 X 轴
      const y = (lat - latRange.min) / (latRange.max - latRange.min) * 1000;  // 纬度映射到 Y 轴
      const z = 0;  // 假设地面海拔为 0
      return new THREE.Vector3(x, y, z);
  }
    
    async componentDidMount() {
      // 在组件挂载后执行逻辑
      // 获取地址栏？id=123参数
      document.title = 'Lo娘分布地图';
      const urlParams = this.getHashQueryParams();
      const id = urlParams.get('id');
      this.setState({
        id
      })
      const _this = this
      const webGldom = document.getElementById('webgl');
      app.init(webGldom, _this);
      // 设置平移
      app.controls.mouseButtons = {
				// LEFT: THREE.MOUSE.PAN,
				MIDDLE: THREE.MOUSE.DOLLY,
				RIGHT: THREE.MOUSE.ROTATE
			}
			app.controls.touches = { 
        // ONE: THREE.TOUCH.PAN,
        TWO: THREE.TOUCH.DOLLY_PAN
      };
      
      
      // const { latRange, lonRange } = this.calculateLatLonRange(geojson)
      // this.setState({
      //   latRange,
      //   lonRange
      // })
      // 将北京的经纬度转换为三维坐标
      // const cameraPosition = this.latLonToXYZ(39.9042, 116.4074);
      app.textFont = await app.createFont()
      const features = []
      geojson.features.forEach((item) => {
        if (item.properties.name !== '') {
          features.push({ 
            name: item.properties.name,
            center: item.properties.center,
            count: 0
          })
        }
      })
      this.setState({
        features
      })
      this.getDistributedAndCreate()
      app.focusOnLatLng(31.51, 121.4, 5, 0)

      // 初始化变量
    let isDragging = false;
    let previousMousePosition = {
        x: 0,
        y: 0
    };
      document.addEventListener('mousedown', function(event) {
          if (event.button === 0) { // 左键
              isDragging = true;
          }
      });
      
      // 鼠标松开事件
      document.addEventListener('mouseup', function(event) {
          if (event.button === 0) { // 左键
              isDragging = false;
          }
      });
      
      // 鼠标移动事件
      document.addEventListener('mousemove', function(event) {
          if (isDragging) {
              const deltaMove = {
                  x: event.offsetX - previousMousePosition.x,
                  y: event.offsetY - previousMousePosition.y
              };
              // console.log(deltaMove)
              app.controls.target.x -= deltaMove.x * 0.1
              app.controls.target.y += deltaMove.y * 0.1
              app.camera.position.x = app.controls.target.x
              app.camera.position.y = app.controls.target.y - 40 * app.camera.position.z / 40
              app.camera.lookAt(app.controls.target)
          }
      
          previousMousePosition = {
              x: event.offsetX,
              y: event.offsetY
          };
      });
      
      // 触摸开始事件
      document.addEventListener('touchstart', function(event) {
          if (event.touches.length === 1) { // 单指
              isDragging = true;
              const touch = event.touches[0];
              previousMousePosition = {
                x: touch.clientX,
                y: touch.clientY
            };
          }
      });
      
      // 触摸结束事件
      document.addEventListener('touchend', function(event) {
        isDragging = false;
          // if (event.touches.length === 0) { // 无手指
          //     isDragging = false;
          // }
      });
      
      // 触摸移动事件
      document.addEventListener('touchmove', function(event) {
          if (isDragging && event.touches.length === 1) {
              const touch = event.touches[0];
              const deltaMove = {
                  x: touch.clientX - previousMousePosition.x,
                  y: touch.clientY - previousMousePosition.y
              };
              app.controls.target.x -= deltaMove.x * 0.1
              app.controls.target.y += deltaMove.y * 0.1
              app.camera.position.x = app.controls.target.x
              app.camera.position.y = app.controls.target.y - 40 * app.camera.position.z / 40
              app.camera.lookAt(app.controls.target)
              // const deltaRotationQuaternion = new THREE.Quaternion()
              //     .setFromEuler(new THREE.Euler(
              //         toRadians(deltaMove.y * 1),
              //         toRadians(deltaMove.x * 1),
              //         0,
              //         'XYZ'
              //     ));
      
              // cube.quaternion.multiplyQuaternions(deltaRotationQuaternion, cube.quaternion);
      
              previousMousePosition = {
                  x: touch.clientX,
                  y: touch.clientY
              };
          }
      });
      
      // 辅助函数：将角度转换为弧度
      function toRadians(angle) {
          return angle * (Math.PI / 180);
      }
    
    }
    /**
     * 计算省份分布排名
     * @param {Array} features - 包含 { name, count } 的数组
     * @param {number} [topN] - 仅返回前 N 名（可选）
     * @returns {Array} 排名后的结果，每项包含 { rank, name, count, percent }
     */
    rankDistribution(features, topN = null) {
      const total = features.reduce((sum, f) => sum + (f.count || 0), 0);
      const sorted = [...features]
        .filter(f => f.count > 0)
        .sort((a, b) => b.count - a.count)
        .map((f, index) => ({
          rank: index + 1,
          name: f.name,
          count: f.count,
          percent: total > 0 ? ((f.count / total) * 100).toFixed(2) + '%' : '0%'
        }));
      return topN ? sorted.slice(0, topN) : sorted;
    }
    // 获取数据并且创建圆柱
    getDistributedAndCreate () {
      getDistributedMaps()
        .then((res) => {
          const { data } = res
          let count = 0
          let { features } = this.state
          features = features.map((child) => {
            child.count = 0
            return {
              ...child
            }
          })
          
          data.forEach((child) => {
            const index = features.findIndex((item) => {
              return item.name.includes(child.ip_location)
            })
            if (index !== -1) {
              features[index].count = child.COUNT
              geojson.features[index].count = child.COUNT
              count += child.COUNT
            }
          })
          const rankedList = this.rankDistribution(features);
          console.log(rankedList, '排行榜');
          this.setState({
            rank_list: rankedList
          })
          // ✅ 给中国省份排名
        const provinceName = [
          '北京市', '天津市', '河北省', '山西省', '内蒙古自治区', '辽宁省', '吉林省', '黑龙江省',
          '上海市', '江苏省', '浙江省', '安徽省', '福建省', '江西省', '山东省', '河南省',
          '湖北省', '湖南省', '广东省', '广西壮族自治区', '海南省', '重庆市', '四川省', '贵州省',
          '云南省', '西藏自治区', '陕西省', '甘肃省', '青海省', '宁夏回族自治区', '新疆维吾尔自治区',
          '台湾省', '香港特别行政区', '澳门特别行政区'
        ];
        const chinaFeaturesWithIndex = geojson.features
        .map((f, i) => ({ feature: f, index: i }))
        .filter(item => provinceName.includes(item.feature.properties.name));
        chinaFeaturesWithIndex
        .sort((a, b) => (b.feature.count || 0) - (a.feature.count || 0))
        .forEach((item, i) => {
          geojson.features[item.index].rank = i + 1;
        });
          console.log('features区块', features, geojson)
          
          const province = new THREE.Group();
          features.forEach((child) => {
            if (child.count > 0 && child.center) {
              try {
                const cyl = app.createCylinderAtLatLng(child.center[1], child.center[0], (child.count / count) * 20, child.name + ' ' + child.count)
                province.add(cyl)
              } catch (error) {
                console.log(error)
              }
            }
          })
          if (app.province) {
              app.scene.remove(app.province);
              app.province = null
          }
          app.province = province
          app.scene.add(province)
          console.log('总数', count)
          const group = app.createGeoJsonMap(geojson, { totalCount: count })
          app.objects = group.children
          app.scene.add(group)
        })
    }
    calculateLatLonRange(geojson) {
      let latRange = { min: Infinity, max: -Infinity };
      let lonRange = { min: Infinity, max: -Infinity };
  
      geojson.features.forEach(feature => {
          if (feature.geometry.type === 'Point') {
              // const [lon, lat] = feature.geometry.coordinates;
              // latRange.min = Math.min(latRange.min, lat);
              // latRange.max = Math.max(latRange.max, lat);
              // lonRange.min = Math.min(lonRange.min, lon);
              // lonRange.max = Math.max(lonRange.max, lon);
          } else if (feature.geometry.type === 'Polygon' || feature.geometry.type === 'MultiPolygon') {
              // feature.geometry.coordinates.forEach(polygon => {
              //     polygon.forEach(ring => {
              //         ring.forEach(([lon, lat]) => {
              //             latRange.min = Math.min(latRange.min, lat);
              //             latRange.max = Math.max(latRange.max, lat);
              //             lonRange.min = Math.min(lonRange.min, lon);
              //             lonRange.max = Math.max(lonRange.max, lon);
              //         });
              //     });
              // });
          }
      });
  
      return { latRange, lonRange };
  }
    getHashQueryParams() {
      const hash = window.location.hash;
      const hashWithoutHashSymbol = hash.slice(1);
      const questionIndex = hashWithoutHashSymbol.indexOf('?');
      if (questionIndex !== -1) {
          const queryString = hashWithoutHashSymbol.slice(questionIndex + 1);
          return new URLSearchParams(queryString);
      }
      return new URLSearchParams();
  }
  render() {
      const { rank_list } = this.state
      return (
          <div className="lolita-wrap">
            <RankingList data={rank_list} />
            <div id="webgl"></div>
          </div>
      );
  }
}

export default Index;
